OBJS_MODULE_SRC = isnan.o \
		  parameter.o \
		  namelist.o \
		  com_var.o \
		  mim_var.o \
		  grads.o \
		  biseki.o \
		  biseki_y.o \
          diabatic_all.o \
          az_latprof.o

OBJS_SRC = mim.o \
	   getpt.o \
	   getpt_etc.o \
	   intpl.o \
	   setpt0.o \
	   w_from_st.o \
	   epflux_div.o \
	   calendar.o \
	   fft.o \
	   undef.o \
	   integral.o \
	   get_pt_dot.o \
	   get_phi_dagger.o \
	   derivative.o \
	   mount_modify.o \
	   energy.o \
	   energy_conv.o \
	   energy_tendency.o \
	   check_range.o \
	   get_z_pt.o \
	   epflux.o \
	   gflux.o \
	   get_var_w_x_zm.o \
	   diabatic.o \
	   get_w.o

